//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua.
        /// </summary>
        internal static string BuyIt {
            get {
                return ResourceManager.GetString("BuyIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xác thực.
        /// </summary>
        internal static string checking {
            get {
                return ResourceManager.GetString("checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng cửa.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận Xét.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tham gia.
        /// </summary>
        internal static string createdDate {
            get {
                return ResourceManager.GetString("createdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GỬI.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xác thực.
        /// </summary>
        internal static string shopchecked {
            get {
                return ResourceManager.GetString("shopchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình Trạng.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string txtTopProductPane {
            get {
                return ResourceManager.GetString("txtTopProductPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghé thăm shop .
        /// </summary>
        internal static string visitShop {
            get {
                return ResourceManager.GetString("visitShop", resourceCulture);
            }
        }
    }
}
